repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: flake8
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
- repo: https://github.com/PyCQA/isort
  rev: 5.6.4
  hooks:
    - id: isort
      args: ["-m", "3", "--tc"]
- repo: local
  hooks:
    - id: install typeshed
      name: typeshed
      entry: bash -c 'git clone -q https://github.com/python/typeshed.git || (cd typeshed && git checkout 9af49c0)'
      language: system
      pass_filenames: false