version: "3"
services:
  db:
    image: postgres:10
    restart: always
    container_name: hlambda_postgres
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./initdb/:/docker-entrypoint-initdb.d/

  web:
    build: .
    container_name: hlambda_api
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      SENTRY_KEY: ${SENTRY_KEY}
      SENTRY_PROJECT: ${SENTRY_PROJECT}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      APP_URL: ${APP_URL}
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
