# Generated by Django 2.2.5 on 2020-01-13 13:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_handler', '0009_auto_20200109_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='outputs',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
