# Generated by Django 2.2.10 on 2020-08-19 17:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_handler', '0020_workflownotification_last_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[]),
        ),
        migrations.AddField(
            model_name='workflow',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[]),
        ),
    ]
