# Generated by Django 2.2.10 on 2020-08-24 16:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_handler", "0021_auto_20200819_1731"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="data",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=list
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="inputs",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="task",
            name="outputs",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="data",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=list
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="inputs",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="outputs",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
