# Generated by Django 2.2.5 on 2020-01-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_handler", "0008_task_disabled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="disabled",
        ),
        migrations.AddField(
            model_name="workflow",
            name="disabled",
            field=models.BooleanField(default=False),
        ),
    ]
