# Generated by Django 2.2.10 on 2020-06-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_handler", "0017_auto_20200611_1522"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="name",
            field=models.CharField(max_length=140),
        ),
    ]
