# Generated by Django 2.2.10 on 2020-08-24 16:14

from django.db import migrations

import human_lambdas.workflow_handler.fields


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_handler", "0021_auto_20200819_1731"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="data",
            field=human_lambdas.workflow_handler.fields.JSONField(
                blank=True, default=list
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="inputs",
            field=human_lambdas.workflow_handler.fields.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="task",
            name="outputs",
            field=human_lambdas.workflow_handler.fields.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="data",
            field=human_lambdas.workflow_handler.fields.JSONField(
                blank=True, default=list
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="inputs",
            field=human_lambdas.workflow_handler.fields.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="outputs",
            field=human_lambdas.workflow_handler.fields.JSONField(default=list),
        ),
    ]
