name: Deploy-AWS-ElasticBeanstalk
env:
  EB_APPLICATION_NAME       : "human-lambdas"
  EB_ENVIRONMENT_NAME       : "human-lambdas-api"
  AWS_REGION_NAME           : "eu-west-2"

on:
  push:
    branches:
    - master

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Configure my AWS Credentils
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}

      - name: Create new ElasticBeanstalk Applicaiton Version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name ${{ env.EB_APPLICATION_NAME }} \
          --version-label "Ver-${{ github.sha }}" \
          --description "CommitSHA-${{ github.sha }}"
      - name: Deploy our new Application Version
        run: aws elasticbeanstalk update-environment --environment-name ${{ env.EB_ENVIRONMENT_NAME }} --version-label "Ver-${{ github.sha }}"

      - name: Print nice message on completion of CD Pipeline
        run: echo "CD Pipeline part finished successfully"

