on:
  release:
    types: [published]
jobs:
  pkg:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: pip install poetry
    - run: poetry version ${GITHUB_REF:10}
    - run: make
    - uses: actions/upload-artifact@v2
      with:
        name: package
        path: dist/* 
    - run: |
        cat > ~/.pypirc <<- EOM
        [pypi]
        username = __token__
        password = ${{ secrets.PYPI_TOKEN }}

        [testpypi]
        username = __token__
        password = ${{ secrets.TEST_PYPI_TOKEN }}
        EOM
    - run: poetry run twine upload --repository pypi dist/*
    - run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
    - run: docker tag "hlambdas/human-lambdas:latest" "hlambdas/human-lambdas:${GITHUB_REF:10}" # e.g. :v1.0.44
    - run: docker tag "hlambdas/human-lambdas:latest" "hlambdas/human-lambdas:${GITHUB_REF:10:12}" # e.g. :v1
    - run: docker push -a "hlambdas/human-lambdas"
