on:
  pull_request:
  push:
    branches:
      - master
jobs:
  pkg:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: make
    - uses: actions/upload-artifact@v2
      with:
        name: package
        path: dist/*