name: Python Tests

on: 
  pull_request:    
    branches:
    - master
    - develop   
  push:
    branches:
    - master
    - develop

jobs:
  vm-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10  
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - name: Dockerize and test
      env:
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        POSTGRES_HOST: localhost
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: |
        docker build . --file Dockerfile --tag hl_rest_api
        env > env_file && docker run --env-file env_file hl_rest_api python manage.py migrate; python manage.py test

