name: Python Tests

on: 
  pull_request:    
    branches:
    - master
    - develop

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10  
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: "test"
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 10

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt-get install libpq-dev
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-dev.txt
    - uses: pre-commit/action@v2.0.0
      with:
        extra_args: --verbose --all-files
    - name: Test with pytest
    - run: python manage.py migrate
    - run: |
        export POSTGRES_USER="postgres"
        export POSTGRES_PASSWORD="test"
        export POSTGRES_DB="postgres"
        export POSTGRES_PORT="${{ job.services.postgres.ports[5432] }}"
        export POSTGRES_HOST="localhost"
        export SECRET_KEY="${{ secrets.SECRET_KEY }}"
        export SENTRY_KEY="${{ secrets.SENTRY_KEY }}"
        export SENTRY_PROJECT="${{ secrets.SENTRY_PROJECT }}"
        export SENDGRID_API_KEY="${{ secrets.SENDGRID_API_KEY }}"
        export DEBUG="True"
        export APP_URL="https://app.humanlambdas.com/"
        export SEGMENT_KEY="${{ secrets.SEGMENT_KEY }}"
        export NOTIFICATION_ASM_GROUPID="${{ secrets.NOTIFICATION_ASM_GROUPID }}"
        export INVITATION_TEMPLATE="test"
        export ACCOUNT_ASM_GROUPID="10101"
        export FORGOTTEN_PASSWORD_TEMPLATE="test"
        export API_URL="http://localhost:8000"
        export HL_CLIENT_API_KEY="${{ secrets.HL_CLIENT_API_KEY }}"
        export HL_ORG_ID="61"

        pytest
