name: Test Publish to PYPI
on: [pull_request]
jobs:
  pypi:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install poetry
      - name: Set poetry version to dev
        run: |
          build_version="$(poetry version -s).dev$(date +%s)"
          poetry version $build_version
      - run: make
      - run: |
          cat > ~/.pypirc <<- EOM
          [pypi]
          username = __token__
          password = ${{ secrets.PYPI_TOKEN }}

          [testpypi]
          username = __token__
          password = ${{ secrets.TEST_PYPI_TOKEN }}
          EOM
      - run: poetry run twine upload --repository testpypi dist/*

  docker:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build . -t "hlambdas/human-lambdas:$GITHUB_SHA"
      - run: docker push "hlambdas/human-lambdas:$GITHUB_SHA"