name: Test Publish to PYPI
on: [pull_request]
jobs:
  build-n-publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
      - run: pip install poetry
      - name: Set poetry version to dev
        run: |
          build_version="$(poetry version -s).dev$(date +%s)"
          poetry version $build_version
      - run: make
      - run: |
          cat > ~/.pypirc <<- EOM
          [pypi]
          username = __token__
          password = ${{ secrets.PYPI_TOKEN }}
          
          [testpypi]
          username = __token__
          password = ${{ secrets.TEST_PYPI_TOKEN }}
          EOM
      - run: twine upload --repository testpypi dist/*